version: 2
jobs:
  build:
    working_directory: /app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
      - deploy:
          name: Push application Docker image
          command: |
            make deploy